### ISSUE TITLE
sth wrong with VS2019 and mingw while compiling

### ISSUE THREAD

**Issue by Bijiazhou** [EricZinda/InductorHtn#1] opened 2021-02-09 05:06 UTC
hi，dear developer
First of all, thank you for your project, which is very **helpful and valuable**，and i try to test this project i find sth wrong with vs2019 in win10（ub18 and macos worded well），and i also try mingw32，also cant work。
Here are the specific problems encountered：
1.in vs2019 ，cmake --detail with error
after `cmake --build ./ --config Debug`
open the sln file with vs2019 and set runtests as  default project then  here is error:
`C:\Users\Administrator\Desktop\InductorHtn-master\src\Tests\Prolog\HtnGoalResolverTests.cpp(175): error: Failure in HtnGoalResolverSquareScenarioTest: Unhandled exception: Internal Error -- file: C:\Users\Administrator\Desktop\InductorHtn-master\src\FXPlatform\Prolog\HtnRuleSet.cpp, line:148
C:\Users\Administrator\Desktop\InductorHtn-master\src\Tests\Prolog\HtnGoalResolverTests.cpp(247): error: Failure in HtnGoalResolverRecursionTests: Unhandled exception: Internal Error -- file: C:\Users\Administrator\Desktop\InductorHtn-master\src\FXPlatform\Prolog\HtnRuleSet.cpp, line:148
C:\Users\Administrator\Desktop\InductorHtn-master\src\Tests\Prolog\HtnGoalResolverTests.cpp(528): error: Failure in HtnGoalResolverUnifierOperatorTests: Unhandled exception: Internal Error -- file: C:\Users\Administrator\Desktop\InductorHtn-master\src\FXPlatform\Prolog\HtnRuleSet.cpp, line:148
C:\Users\Administrator\Desktop\InductorHtn-master\src\Tests\Prolog\HtnGoalResolverTests.cpp(591): error: Failure in HtnGoalResolverListTests: Unhandled exception: Internal Error -- file: C:\Users\Administrator\Desktop\InductorHtn-master\src\FXPlatform\Prolog\HtnRuleSet.cpp, line:148
C:\Users\Administrator\Desktop\InductorHtn-master\src\Tests\Prolog\HtnGoalResolverTests.cpp(712): error: Failure in HtnGoalResolverAtomDowncaseTests: Unhandled exception: Internal Error -- file: C:\Users\Administrator\Desktop\InductorHtn-master\src\FXPlatform\Prolog\HtnRuleSet.cpp, line:148
C:\Users\Administrator\Desktop\InductorHtn-master\src\Tests\Prolog\HtnGoalResolverTests.cpp(750): error: Failure in HtnGoalResolverAtomConcatTests: Unhandled exception: Internal Error -- file: C:\Users\Administrator\Desktop\InductorHtn-master\src\FXPlatform\Prolog\HtnRuleSet.cpp, line:148
C:\Users\Administrator\Desktop\InductorHtn-master\src\Tests\Prolog\HtnGoalResolverTests.cpp(876): error: Failure in HtnGoalResolverVariableTests: Unhandled exception: Internal Error -- file: C:\Users\Administrator\Desktop\InductorHtn-master\src\FXPlatform\Prolog\HtnRuleSet.cpp, line:148
C:\Users\Administrator\Desktop\InductorHtn-master\src\Tests\Prolog\HtnGoalResolverTests.cpp(995): error: Failure in HtnGoalResolverForAllTests: Unhandled exception: Internal Error -- file: C:\Users\Administrator\Desktop\InductorHtn-master\src\FXPlatform\Prolog\HtnRuleSet.cpp, line:148
C:\Users\Administrator\Desktop\InductorHtn-master\src\Tests\Prolog\HtnGoalResolverTests.cpp(1191): error: Failure in HtnGoalResolverCutTests: Unhandled exception: Internal Error -- file: C:\Users\Administrator\Desktop\InductorHtn-master\src\FXPlatform\Prolog\HtnRuleSet.cpp, line:148
C:\Users\Administrator\Desktop\InductorHtn-master\src\Tests\Prolog\HtnGoalResolverTests.cpp(1313): error: Failure in HtnGoalResolverAssertRetractTests: Unhandled exception: Internal Error -- file: C:\Users\Administrator\Desktop\InductorHtn-master\src\FXPlatform\Prolog\HtnRuleSet.cpp, line:148
C:\Users\Administrator\Desktop\InductorHtn-master\src\Tests\Prolog\HtnGoalResolverTests.cpp(1422): error: Failure in HtnGoalResolverFindAllTests: Unhandled exception: Internal Error -- file: C:\Users\Administrator\Desktop\InductorHtn-master\src\FXPlatform\Prolog\HtnRuleSet.cpp, line:148
C:\Users\Administrator\Desktop\InductorHtn-master\src\Tests\Prolog\HtnGoalResolverTests.cpp(1561): error: Failure in HtnGoalResolverMinTests: Unhandled exception: Internal Error -- file: C:\Users\Administrator\Desktop\InductorHtn-master\src\FXPlatform\Prolog\HtnRuleSet.cpp, line:148
C:\Users\Administrator\Desktop\InductorHtn-master\src\Tests\Prolog\HtnGoalResolverTests.cpp(1634): error: Failure in HtnGoalResolverMaxTests: Unhandled exception: Internal Error -- file: C:\Users\Administrator\Desktop\InductorHtn-master\src\FXPlatform\Prolog\HtnRuleSet.cpp, line:148
C:\Users\Administrator\Desktop\InductorHtn-master\src\Tests\Prolog\HtnGoalResolverTests.cpp(1707): error: Failure in HtnGoalResolverSumTests: Unhandled exception: Internal Error -- file: C:\Users\Administrator\Desktop\InductorHtn-master\src\FXPlatform\Prolog\HtnRuleSet.cpp, line:148
C:\Users\Administrator\Desktop\InductorHtn-master\src\Tests\Prolog\HtnGoalResolverTests.cpp(1780): error: Failure in HtnGoalResolverDistinctTests: Unhandled exception: Internal Error -- file: C:\Users\Administrator\Desktop\InductorHtn-master\src\FXPlatform\Prolog\HtnRuleSet.cpp, line:148
C:\Users\Administrator\Desktop\InductorHtn-master\src\Tests\Prolog\HtnGoalResolverTests.cpp(1852): error: Failure in HtnGoalResolverCountTests: Unhandled exception: Internal Error -- file: C:\Users\Administrator\Desktop\InductorHtn-master\src\FXPlatform\Prolog\HtnRuleSet.cpp, line:148
C:\Users\Administrator\Desktop\InductorHtn-master\src\Tests\Prolog\HtnGoalResolverTests.cpp(1920): error: Failure in HtnGoalResolverSortByTests: Unhandled exception: Internal Error -- file: C:\Users\Administrator\Desktop\InductorHtn-master\src\FXPlatform\Prolog\HtnRuleSet.cpp, line:148
C:\Users\Administrator\Desktop\InductorHtn-master\src\Tests\Prolog\HtnGoalResolverTests.cpp(1973): error: Failure in HtnGoalResolverIdenticalTests: Unhandled exception: Internal Error -- file: C:\Users\Administrator\Desktop\InductorHtn-master\src\FXPlatform\Prolog\HtnRuleSet.cpp, line:148
C:\Users\Administrator\Desktop\InductorHtn-master\src\Tests\Prolog\HtnGoalResolverTests.cpp(2174): error: Failure in HtnGoalResolverNotTests: Unhandled exception: Internal Error -- file: C:\Users\Administrator\Desktop\InductorHtn-master\src\FXPlatform\Prolog\HtnRuleSet.cpp, line:148
C:\Users\Administrator\Desktop\InductorHtn-master\src\Tests\Prolog\HtnGoalResolverTests.cpp(2235): error: Failure in HtnGoalResolverFirstTests: Unhandled exception: Internal Error -- file: C:\Users\Administrator\Desktop\InductorHtn-master\src\FXPlatform\Prolog\HtnRuleSet.cpp, line:148
C:\Users\Administrator\Desktop\InductorHtn-master\src\Tests\Prolog\HtnGoalResolverTests.cpp(2285): error: Failure in HtnGoalResolverPrintTests: Unhandled exception: Internal Error -- file: C:\Users\Administrator\Desktop\InductorHtn-master\src\FXPlatform\Prolog\HtnRuleSet.cpp, line:148
C:\Users\Administrator\Desktop\InductorHtn-master\src\Tests\Prolog\HtnGoalResolverTests.cpp(2334): error: Failure in HtnGoalResolverResolveTests: Unhandled exception: Internal Error -- file: C:\Users\Administrator\Desktop\InductorHtn-master\src\FXPlatform\Prolog\HtnRuleSet.cpp, line:148
C:\Users\Administrator\Desktop\InductorHtn-master\src\Tests\Prolog\PrologCompilerTests.cpp(216): error: Failure in PrologListCompileTests: Unhandled exception: Internal Error -- file: C:\Users\Administrator\Desktop\InductorHtn-master\src\FXPlatform\Prolog\HtnRuleSet.cpp, line:148
C:\Users\Administrator\Desktop\InductorHtn-master\src\Tests\Htn\HtnPlannerTests.cpp(214): error: Failure in PlannerNormalMethodTest: Unhandled exception: Internal Error -- file: C:\Users\Administrator\Desktop\InductorHtn-master\src\FXPlatform\Prolog\HtnRuleSet.cpp, line:148
C:\Users\Administrator\Desktop\InductorHtn-master\src\Tests\Htn\HtnPlannerTests.cpp(371): error: Failure in PlannerSetOfTest: Unhandled exception: Internal Error -- file: C:\Users\Administrator\Desktop\InductorHtn-master\src\FXPlatform\Prolog\HtnRuleSet.cpp, line:148
C:\Users\Administrator\Desktop\InductorHtn-master\src\Tests\Htn\HtnPlannerTests.cpp(682): error: Failure in PlannerSingleSolutionTest: Unhandled exception: Internal Error -- file: C:\Users\Administrator\Desktop\InductorHtn-master\src\FXPlatform\Prolog\HtnRuleSet.cpp, line:148
C:\Users\Administrator\Desktop\InductorHtn-master\src\Tests\Htn\HtnPlannerTests.cpp(742): error: Failure in PlannerTryTest: Unhandled exception: Internal Error -- file: C:\Users\Administrator\Desktop\InductorHtn-master\src\FXPlatform\Prolog\HtnRuleSet.cpp, line:148
C:\Users\Administrator\Desktop\InductorHtn-master\src\Tests\Htn\HtnPlannerTests.cpp(880): error: Failure in PlannerElseTest: Unhandled exception: Internal Error -- file: C:\Users\Administrator\Desktop\InductorHtn-master\src\FXPlatform\Prolog\HtnRuleSet.cpp, line:148
C:\Users\Administrator\Desktop\InductorHtn-master\src\Tests\Htn\HtnPlannerTests.cpp(991): error: Failure in PlannerFirstSortByNot: Unhandled exception: Internal Error -- file: C:\Users\Administrator\Desktop\InductorHtn-master\src\FXPlatform\Prolog\HtnRuleSet.cpp, line:148
C:\Users\Administrator\Desktop\InductorHtn-master\src\Tests\Htn\HtnPlannerTests.cpp(1142): error: Failure in PlannerShopTransportationScenarioTest: Unhandled exception: Internal Error -- file: C:\Users\Administrator\Desktop\InductorHtn-master\src\FXPlatform\Prolog\HtnRuleSet.cpp, line:148
C:\Users\Administrator\Desktop\InductorHtn-master\src\Tests\Htn\HtnPlannerTests.cpp(1396): error: Failure in HtnPlannerMemoryBudgetTest: Unhandled exception: Internal Error -- file: C:\Users\Administrator\Desktop\InductorHtn-master\src\FXPlatform\Prolog\HtnRuleSet.cpp, line:148
FAILURE: 31 out of 61 tests failed (31 failures). search for "error: Failure in" to find the error` 

![1612845657(1)](https://user-images.githubusercontent.com/30489991/107316682-1ef64880-6ad4-11eb-92d8-9a8ec8da4432.jpg)

 
2.in mingw-32，.\runtests.exe with error
![image](https://user-images.githubusercontent.com/30489991/107316747-451be880-6ad4-11eb-86be-d65c73910dce.png)

and runing examples with error 
``
 
![image](https://user-images.githubusercontent.com/30489991/107316845-78f70e00-6ad4-11eb-8338-fae2143171aa.png)

`terminate called without an active exception`

**Comment by EricZinda** [comment] 2021-02-09 17:12
Thanks for reporting @YCY1997!  I haven't tried with mingw-32 yet or Windows 10.  I'll see if I can get both installed this week and reproduce the issue.  Definitely looks very odd.

**Comment by Bijiazhou** [comment] 2021-02-11 03:49
Duplicate of #
hi ,after a few hours trying ,I fortunately found that it cant working well in win10 while I just using **clion** to compile and run the code in the `src` folder,like this:
![image](https://user-images.githubusercontent.com/30489991/107599867-f8174e00-6c5c-11eb-9836-4c786d1bd540.png)，while the build tools is also **mingw-32**，vs2019 never worked.

then，when i using it in Xcode,i found you'd better add this code in `CMakeLists.txt`，otherwise, it cannot be compiled.
` set(CMAKE_C_COMPILER "gcc")`
`set(CMAKE_CXX_COMPILER "g++")`
,just like this
![image](https://user-images.githubusercontent.com/30489991/107600292-437e2c00-6c5e-11eb-8fc0-a1585470c037.png)


finally, I read your blog about HTN planner, I have to say, it's really cool.

**Comment by EricZinda** [comment] 2021-02-12 16:25
This is all great information! Thanks so much.  Unfortunately I'm out of office next week so it will be a bit before I can dig in.  I'll tackle it first thing when I get back the following week.

**Comment by EricZinda** [comment] 2021-02-23 02:05
OK, I was able to reproduce the issue with VS2019 and windows 8.  I fixed a couple of different bugs and it should be working on that platform now.  All but one got introduced in some recent changes.  My fault for not testing on windows.  The last one seems to be a compiler optimization bug that only appears in the release build (I don't think you hit that one but I fixed it anyway).

Can you tell me if this fixes it in windows 10 and mingw-32?

**Comment by Bijiazhou** [comment] 2021-03-03 12:22
ok,i'll try to test it in win10 and mingw 32 / 64，and If  have any questions, I will give you feedback as soon as possible

**Comment by Bijiazhou** [comment] 2021-03-06 10:53
after my test，if using cmake with **mingw-32** in win10，it could compiled， but sth wrong with runtest.exe, just like :
![image](https://user-images.githubusercontent.com/30489991/110203676-78bb1a00-7eaa-11eb-810d-4eb15020af40.png)

of course,it cant run examples:
  
![image](https://user-images.githubusercontent.com/30489991/110203729-bc158880-7eaa-11eb-86cc-e20f5f3ca3e7.png)

but good news is it worked well with **VS2019** which is a great improvement:
![image](https://user-images.githubusercontent.com/30489991/110204036-f4699680-7eab-11eb-8275-af7f39b21c42.png)

**Comment by EricZinda** [comment] 2021-03-08 20:07
Great, thanks for trying this out.  I'll see if I can find out what is going wrong with mingw-32

**Comment by EricZinda** [comment] 2021-03-08 21:05
I tried building and running tests on Win8 (I realize you are on win10) and mingw with these settings:

![image](https://user-images.githubusercontent.com/2416921/110381437-aae98a80-8016-11eb-92ad-17ee072d4ebb.png)

and it worked:

~~~
>cmake -G "MinGW Makefiles" ..\src
...

>cmake --build ./ --config Debug
...

>runtests.exe
Success: 61 tests passed.
Test time: 1.87 seconds.
~~~

Do you know what settings you have for mingw?

**Comment by EricZinda** [comment] 2023-04-07 16:19
Closing since there doesn't seem to be any activity on this and I couldn't reproduce the problem.

**Closed as completed by EricZinda** 2023-04-07 16:19 UTC
